export default {
  index: 'Overview',
  write: 'POST /v1/memory/write',
  'recall-text': 'POST /v1/memory/recall_text',
  'planning-context': 'POST /v1/memory/planning/context',
  'context-assemble': 'POST /v1/memory/context/assemble',
  'rules-state': 'POST /v1/memory/rules/state',
  'rules-evaluate': 'POST /v1/memory/rules/evaluate',
  find: 'POST /v1/memory/find',
  resolve: 'POST /v1/memory/resolve',
  'tools-select': 'POST /v1/memory/tools/select',
  'tools-decision': 'POST /v1/memory/tools/decision',
  'tools-run': 'POST /v1/memory/tools/run',
  'tools-feedback': 'POST /v1/memory/tools/feedback',
  handoff: 'Handoff Store and Recover',
  'replay-run-get': 'POST /v1/memory/replay/runs/get',
  'replay-playbook-get': 'POST /v1/memory/replay/playbooks/get',
  'replay-playbook-candidate': 'POST /v1/memory/replay/playbooks/candidate',
  'replay-compile-from-run': 'POST /v1/memory/replay/playbooks/compile_from_run',
  'replay-run': 'POST /v1/memory/replay/playbooks/run',
  'replay-dispatch': 'POST /v1/memory/replay/playbooks/dispatch',
  'replay-candidate-dispatch': 'Replay Candidate and Dispatch',
  'replay-repair-review': 'POST /v1/memory/replay/playbooks/repair/review'
}
