import { defineConfig } from "vitepress";

export default defineConfig({
  lang: "en-US",
  site: "https://doc.aionisos.com",
  title: "Aionis Docs",
  description: "A verifiable, operable memory kernel for agent systems.",
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  srcExclude: [
    "**/COMMERCIAL_STRATEGY.md",
    "**/EXTERNAL_RELEASE_PRODUCT_PLAN.md",
    "**/GO_TO_MARKET_*.md",
    "**/GTM_*.md",
    "**/HOSTED_*.md",
    "**/PERFORMANCE_REPORT_V1_TEMPLATE.md",
    "**/PROD_ORCHESTRATION_PARTITION_PLAN.md",
    "**/PRODUCT_SCALE_COGNITION_PRIORITY_PLAN.md",
    "**/THREE_GAPS_PRIORITY_PLAN.md",
    "**/ULTRA_SCALE_ROUTING_MATRIX.md",
    "**/WEBSITE_NEXTJS_HEROUI_SKELETON.md",
    "**/internal/**",
    "**/_site/**",
    "**/_layouts/**",
    "_config.yml",
    "_config.local.yml",
    "**/.vitepress/cache/**",
    "**/.vitepress/dist/**",
    "**/.DS_Store",
  ],
  head: [
    ["meta", { name: "theme-color", content: "#0f172a" }],
    ["meta", { property: "og:title", content: "Aionis Docs" }],
    ["meta", { property: "og:description", content: "Verifiable / Operable Memory Kernel documentation." }],
  ],
  themeConfig: {
    logo: "/logo.svg",
    nav: [
      { text: "Docs Home", link: "/index" },
      { text: "Overview", link: "/public/en/overview/01-overview" },
      { text: "Get Started", link: "/public/en/getting-started/01-get-started" },
      { text: "Core Concepts", link: "/public/en/core-concepts/00-core-concepts" },
      { text: "Architecture", link: "/public/en/architecture/01-architecture" },
      { text: "Context", link: "/public/en/context-orchestration/00-context-orchestration" },
      { text: "Policy Loop", link: "/public/en/policy-execution/00-policy-execution-loop" },
      { text: "Operate", link: "/public/en/operate-production/00-operate-production" },
      { text: "Integrations", link: "/public/en/integrations/00-overview" },
      { text: "API", link: "/public/en/api-reference/00-api-reference" },
      { text: "Benchmarks", link: "/public/en/benchmarks/01-benchmarks" },
      { text: "Roadmap", link: "/public/en/roadmap/00-roadmap" },
      { text: "GitHub", link: "https://github.com/Cognary/Aionis" },
    ],
    sidebar: [
      {
        text: "Overview",
        items: [
          { text: "Docs Home", link: "/index" },
          { text: "Overview", link: "/public/en/overview/01-overview" },
          { text: "Docs Navigation Map", link: "/public/en/overview/02-docs-navigation" },
          { text: "Role-Based Reading Paths", link: "/public/en/overview/03-role-based-paths" },
          { text: "Core Differentiators", link: "/public/en/about/01-core-differentiators" },
          { text: "Aionis Onepage", link: "/public/en/about/02-aionis-onepage" },
        ],
      },
      {
        text: "Get Started",
        items: [
          { text: "Get Started", link: "/public/en/getting-started/01-get-started" },
          { text: "5-Minute Onboarding", link: "/public/en/getting-started/02-onboarding-5min" },
          { text: "Embedding Setup", link: "/public/en/getting-started/03-embedding-setup" },
        ],
      },
      {
        text: "Core Concepts",
        items: [
          { text: "Core Concepts", link: "/public/en/core-concepts/00-core-concepts" },
          { text: "Verifiable Memory Graph", link: "/public/en/core-concepts/01-verifiable-memory-graph" },
          { text: "Derived Artifacts", link: "/public/en/core-concepts/02-derived-artifacts" },
          { text: "Scope and Tenant Isolation", link: "/public/en/core-concepts/03-scope-and-tenant" },
          { text: "Decision and Run Model", link: "/public/en/core-concepts/04-decision-and-run-model" },
        ],
      },
      {
        text: "Architecture",
        items: [
          { text: "Architecture", link: "/public/en/architecture/01-architecture" },
          { text: "Architecture Deep Dive (Supplement)", link: "/public/en/concepts/02-architecture" },
        ],
      },
      {
        text: "Context Orchestration",
        items: [
          { text: "Context Orchestration", link: "/public/en/context-orchestration/00-context-orchestration" },
          { text: "Context Orchestration Deep Dive (Supplement)", link: "/public/en/concepts/01-context-orchestration" },
          { text: "Planner Context", link: "/public/en/reference/02-planner-context" },
          { text: "Build Memory", link: "/public/en/guides/01-build-memory" },
          { text: "Playground", link: "/public/en/guides/02-playground" },
        ],
      },
      {
        text: "Policy & Execution Loop",
        items: [
          { text: "Policy and Execution Loop", link: "/public/en/policy-execution/00-policy-execution-loop" },
          { text: "Control & Policy", link: "/public/en/control/01-control-policy" },
          { text: "Rule Lifecycle", link: "/public/en/control/02-rule-lifecycle" },
          { text: "Execution Loop Gate", link: "/public/en/control/03-execution-loop-gate" },
          { text: "Policy Adaptation Gate", link: "/public/en/control/04-policy-adaptation-gate" },
          { text: "Rule Promotion Governance", link: "/public/en/reference/03-rule-promotion-governance" },
          { text: "Rule Conflict Report", link: "/public/en/reference/04-rule-conflict-report" },
        ],
      },
      {
        text: "Operate & Production",
        items: [
          { text: "Operate and Production", link: "/public/en/operate-production/00-operate-production" },
          { text: "Production Core Gate", link: "/public/en/operations/03-production-core-gate" },
          { text: "Prod Go-Live Gate", link: "/public/en/operations/04-prod-go-live-gate" },
          { text: "Operate Overview", link: "/public/en/operations/00-operate" },
          { text: "Operator Runbook", link: "/public/en/operations/02-operator-runbook" },
          { text: "Ops Console", link: "/public/en/operations/01-ops-console" },
          { text: "E2E Regression", link: "/public/en/operations/05-e2e-regression" },
          { text: "Standalone to HA Runbook", link: "/public/en/operations/06-standalone-to-ha-runbook" },
          { text: "HA Failure Drill Template", link: "/public/en/operations/07-ha-failure-drill-template" },
          { text: "HA Failure Drill Sample", link: "/public/en/operations/08-ha-failure-drill-sample" },
          { text: "Abstraction Policy Runbook", link: "/public/en/operations/09-abstraction-policy-runbook" },
          { text: "Consolidation Replay Runbook", link: "/public/en/operations/10-consolidation-replay-runbook" },
        ],
      },
      {
        text: "Integrations",
        items: [
          { text: "Integrations", link: "/public/en/integrations/00-overview" },
          { text: "MCP Integration", link: "/public/en/integrations/01-mcp" },
          { text: "OpenWork", link: "/public/en/integrations/02-openwork" },
          { text: "LangGraph", link: "/public/en/integrations/03-langgraph" },
        ],
      },
      {
        text: "API Reference",
        items: [
          { text: "API Reference", link: "/public/en/api-reference/00-api-reference" },
          { text: "API Contract", link: "/public/en/api/01-api-contract" },
          { text: "Reference Overview", link: "/public/en/reference/01-reference" },
          { text: "SDK Guide", link: "/public/en/reference/05-sdk" },
          { text: "SDK Compatibility", link: "/public/en/reference/06-sdk-compatibility-matrix" },
          { text: "URI Object Coverage", link: "/public/en/reference/07-uri-expansion-plan" },
        ],
      },
      {
        text: "Benchmarks & Evidence",
        items: [
          { text: "Benchmarks", link: "/public/en/benchmarks/01-benchmarks" },
          { text: "Benchmark Snapshot", link: "/public/en/benchmarks/02-benchmark-snapshot-public" },
          { text: "Performance Baseline", link: "/public/en/benchmarks/05-performance-baseline" },
          { text: "AionisBench v0.1", link: "/public/en/benchmarks/06-aionis-bench-v01" },
          { text: "Differentiation Evidence", link: "/public/en/benchmarks/03-differentiation-evidence" },
          { text: "Governance Weekly Report", link: "/public/en/benchmarks/04-governance-weekly-report" },
        ],
      },
      {
        text: "Roadmap",
        items: [{ text: "Roadmap", link: "/public/en/roadmap/00-roadmap" }],
      },
    ],
    editLink: {
      pattern: "https://github.com/Cognary/Aionis/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/Cognary/Aionis" }],
    footer: {
      message: "Aionis Documentation",
      copyright: "Copyright © Cognary",
    },
    search: {
      provider: "local",
    },
    outline: {
      level: [2, 3],
    },
  },
});
