import { defineConfig } from "vitepress";

export default defineConfig({
  lang: "en-US",
  site: "https://doc.aionisos.com",
  title: "Aionis Docs",
  description: "A verifiable, operable memory kernel for agent systems.",
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  srcExclude: [
    "**/COMMERCIAL_STRATEGY.md",
    "**/EXTERNAL_RELEASE_PRODUCT_PLAN.md",
    "**/GO_TO_MARKET_*.md",
    "**/GTM_*.md",
    "**/HOSTED_*.md",
    "**/PERFORMANCE_REPORT_V1_TEMPLATE.md",
    "**/PROD_ORCHESTRATION_PARTITION_PLAN.md",
    "**/PRODUCT_SCALE_COGNITION_PRIORITY_PLAN.md",
    "**/THREE_GAPS_PRIORITY_PLAN.md",
    "**/ULTRA_SCALE_ROUTING_MATRIX.md",
    "**/WEBSITE_NEXTJS_HEROUI_SKELETON.md",
    "**/internal/**",
    "**/_site/**",
    "**/_layouts/**",
    "_config.yml",
    "_config.local.yml",
    "**/.vitepress/cache/**",
    "**/.vitepress/dist/**",
    "**/.DS_Store",
  ],
  head: [
    ["meta", { name: "theme-color", content: "#0f172a" }],
    ["meta", { property: "og:title", content: "Aionis Docs" }],
    ["meta", { property: "og:description", content: "Verifiable / Operable Memory Kernel documentation." }],
  ],
  themeConfig: {
    logo: "/logo.svg",
    nav: [
      { text: "Why Aionis", link: "/public/en/about/01-core-differentiators" },
      { text: "Get Started", link: "/public/en/getting-started/01-get-started" },
      { text: "Build Memory", link: "/public/en/guides/01-build-memory" },
      { text: "Control & Policy", link: "/public/en/control/01-control-policy" },
      { text: "Operate", link: "/public/en/operations/00-operate" },
      { text: "Integrations", link: "/public/en/integrations/00-overview" },
      { text: "Reference", link: "/public/en/reference/01-reference" },
      { text: "Benchmarks", link: "/public/en/benchmarks/01-benchmarks" },
      { text: "中文", link: "/public/zh/README" },
      { text: "GitHub", link: "https://github.com/Cognary/Aionis" },
    ],
    sidebar: [
      {
        text: "Start",
        items: [
          { text: "Docs Home", link: "/index" },
          { text: "Get Started", link: "/public/en/getting-started/01-get-started" },
          { text: "5-Minute Onboarding", link: "/public/en/getting-started/02-onboarding-5min" },
          { text: "Embedding Setup", link: "/public/en/getting-started/03-embedding-setup" },
          { text: "Core Differentiators", link: "/public/en/about/01-core-differentiators" },
        ],
      },
      {
        text: "Build",
        items: [
          { text: "Build Memory", link: "/public/en/guides/01-build-memory" },
          { text: "Context Orchestration", link: "/CONTEXT_ORCHESTRATION" },
          { text: "Context Orchestrator Plan", link: "/CONTEXT_ORCHESTRATOR_PLAN" },
          { text: "Playground", link: "/public/en/guides/02-playground" },
        ],
      },
      {
        text: "Control",
        items: [
          { text: "Control & Policy", link: "/public/en/control/01-control-policy" },
          { text: "Rule Lifecycle", link: "/public/en/control/02-rule-lifecycle" },
          { text: "Execution Loop Gate", link: "/EXECUTION_LOOP_GATE" },
          { text: "Policy Adaptation Gate", link: "/POLICY_ADAPTATION_GATE" },
        ],
      },
      {
        text: "Operations",
        items: [
          { text: "Operate", link: "/public/en/operations/00-operate" },
          { text: "Operator Runbook", link: "/public/en/operations/02-operator-runbook" },
          { text: "Playground", link: "/public/en/guides/02-playground" },
          { text: "Ops Console", link: "/public/en/operations/01-ops-console" },
          { text: "Prod Go-Live Gate", link: "/public/en/operations/04-prod-go-live-gate" },
          { text: "Production Core Gate", link: "/public/en/operations/03-production-core-gate" },
          { text: "E2E Regression", link: "/public/en/operations/05-e2e-regression" },
          { text: "HA Failure Drill Template", link: "/public/en/operations/07-ha-failure-drill-template" },
          { text: "HA Failure Drill Sample", link: "/public/en/operations/08-ha-failure-drill-sample" },
          { text: "Standalone to HA Runbook", link: "/public/en/operations/06-standalone-to-ha-runbook" },
          { text: "Benchmark Snapshot", link: "/public/en/benchmarks/02-benchmark-snapshot-public" },
        ],
      },
      {
        text: "Integrations",
        items: [
          { text: "Integrations", link: "/public/en/integrations/00-overview" },
          { text: "MCP Integration", link: "/public/en/integrations/01-mcp" },
          { text: "OpenWork", link: "/OPENWORK_INTEGRATION" },
          { text: "LangGraph", link: "/LANGGRAPH_INTEGRATION" },
        ],
      },
      {
        text: "Reference",
        items: [
          { text: "Reference", link: "/public/en/reference/01-reference" },
          { text: "API Contract", link: "/public/en/api/01-api-contract" },
          { text: "SDK Guide", link: "/public/en/reference/05-sdk" },
          { text: "SDK Compatibility", link: "/public/en/reference/06-sdk-compatibility-matrix" },
          { text: "Planner Context", link: "/public/en/reference/02-planner-context" },
          { text: "Rule Promotion Governance", link: "/public/en/reference/03-rule-promotion-governance" },
          { text: "Rule Conflict Report", link: "/public/en/reference/04-rule-conflict-report" },
          { text: "Architecture", link: "/ARCHITECTURE" },
          { text: "Docs Index", link: "/README" },
        ],
      },
      {
        text: "Benchmarks",
        items: [
          { text: "Benchmarks", link: "/public/en/benchmarks/01-benchmarks" },
          { text: "Benchmark Snapshot", link: "/public/en/benchmarks/02-benchmark-snapshot-public" },
          { text: "Performance Baseline", link: "/PERFORMANCE_BASELINE" },
          { text: "AionisBench v0.1", link: "/AIONIS_BENCH_V01" },
          { text: "Differentiation Evidence", link: "/public/en/benchmarks/03-differentiation-evidence" },
          { text: "Governance Weekly Report", link: "/public/en/benchmarks/04-governance-weekly-report" },
        ],
      },
    ],
    editLink: {
      pattern: "https://github.com/Cognary/Aionis/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/Cognary/Aionis" }],
    footer: {
      message: "Aionis Documentation",
      copyright: "Copyright © Cognary",
    },
    search: {
      provider: "local",
    },
    outline: {
      level: [2, 3],
    },
  },
});
