import { defineConfig } from "vitepress";

export default defineConfig({
  lang: "en-US",
  site: "https://doc.aionisos.com",
  title: "Aionis Docs",
  description: "A verifiable, operable memory kernel for agent systems.",
  base: "/",
  cleanUrls: true,
  lastUpdated: true,
  srcExclude: [
    "**/COMMERCIAL_STRATEGY.md",
    "**/EXTERNAL_RELEASE_PRODUCT_PLAN.md",
    "**/GO_TO_MARKET_*.md",
    "**/GTM_*.md",
    "**/HOSTED_*.md",
    "**/PERFORMANCE_REPORT_V1_TEMPLATE.md",
    "**/PROD_ORCHESTRATION_PARTITION_PLAN.md",
    "**/PRODUCT_SCALE_COGNITION_PRIORITY_PLAN.md",
    "**/THREE_GAPS_PRIORITY_PLAN.md",
    "**/ULTRA_SCALE_ROUTING_MATRIX.md",
    "**/WEBSITE_NEXTJS_HEROUI_SKELETON.md",
    "**/_site/**",
    "**/_layouts/**",
    "_config.yml",
    "_config.local.yml",
    "**/.vitepress/cache/**",
    "**/.vitepress/dist/**",
    "**/.DS_Store",
  ],
  head: [
    ["meta", { name: "theme-color", content: "#0f172a" }],
    ["meta", { property: "og:title", content: "Aionis Docs" }],
    ["meta", { property: "og:description", content: "Verifiable / Operable Memory Kernel documentation." }],
  ],
  themeConfig: {
    logo: "/logo.svg",
    nav: [
      { text: "Why Aionis", link: "/index#why-teams-choose-aionis" },
      { text: "Start", link: "/ONBOARDING_5MIN" },
      { text: "Concepts", link: "/ARCHITECTURE" },
      { text: "API", link: "/API_CONTRACT" },
      { text: "SDK", link: "/SDK" },
      { text: "Ops", link: "/OPERATOR_RUNBOOK" },
      { text: "Integrations", link: "/MCP_INTEGRATION" },
      { text: "GitHub", link: "https://github.com/Cognary/Aionis" },
    ],
    sidebar: [
      {
        text: "Start",
        items: [
          { text: "Docs Home", link: "/index" },
          { text: "5-Minute Onboarding", link: "/ONBOARDING_5MIN" },
          { text: "Architecture", link: "/ARCHITECTURE" },
          { text: "Docs Index", link: "/README" },
        ],
      },
      {
        text: "API & SDK",
        items: [
          { text: "API Contract", link: "/API_CONTRACT" },
          { text: "SDK Guide", link: "/SDK" },
          { text: "SDK Compatibility", link: "/SDK_COMPATIBILITY_MATRIX" },
          { text: "Planner Context", link: "/PLANNER_CONTEXT" },
          { text: "Rule Lifecycle", link: "/RULE_LIFECYCLE" },
          { text: "Rule Promotion Governance", link: "/RULE_PROMOTION_GOVERNANCE" },
          { text: "Rule Conflict Report", link: "/RULE_CONFLICT_REPORT" },
          { text: "Execution Loop Gate", link: "/EXECUTION_LOOP_GATE" },
          { text: "Policy Adaptation Gate", link: "/POLICY_ADAPTATION_GATE" },
        ],
      },
      {
        text: "Operations",
        items: [
          { text: "Operator Runbook", link: "/OPERATOR_RUNBOOK" },
          { text: "Ops Console", link: "/OPS_CONSOLE" },
          { text: "Abstraction Policy Runbook", link: "/ABSTRACTION_POLICY_RUNBOOK" },
          { text: "Consolidation Replay Runbook", link: "/CONSOLIDATION_REPLAY_RUNBOOK" },
          { text: "Prod Go-Live Gate", link: "/PROD_GO_LIVE_GATE" },
          { text: "Production Core Gate", link: "/PRODUCTION_CORE_GATE" },
          { text: "E2E Regression", link: "/E2E_REGRESSION" },
          { text: "Two-Phase Migrations", link: "/MIGRATIONS_TWO_PHASE" },
          { text: "Performance Baseline", link: "/PERFORMANCE_BASELINE" },
          { text: "Recall Tail Latency Plan", link: "/RECALL_TAIL_LATENCY_PLAN" },
          { text: "AionisBench v0.1", link: "/AIONIS_BENCH_V01" },
          { text: "Adaptive Compression Plan", link: "/ADAPTIVE_COMPRESSION_PLAN" },
          { text: "Governance Weekly Report", link: "/GOVERNANCE_WEEKLY_REPORT" },
          { text: "Docker Release", link: "/DOCKER_RELEASE" },
        ],
      },
      {
        text: "Integrations",
        items: [
          { text: "MCP Integration", link: "/MCP_INTEGRATION" },
          { text: "OpenWork", link: "/OPENWORK_INTEGRATION" },
          { text: "LangGraph", link: "/LANGGRAPH_INTEGRATION" },
        ],
      },
    ],
    editLink: {
      pattern: "https://github.com/Cognary/Aionis/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/Cognary/Aionis" }],
    footer: {
      message: "Aionis Documentation",
      copyright: "Copyright © Cognary",
    },
    search: {
      provider: "local",
    },
    outline: {
      level: [2, 3],
    },
  },
});
